name: Run Tests

on:
  pull_request:
    branches: [ master, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: LAS2PEERMON
      DB_USER: root
      DB_PASSWORD: root
    steps:
    - name: Set up MySQL
      run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE  ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - run: mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE }} < ./mysql-init-files/initDB.sql
    - name: Grant Gradle permissions
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew clean test --stacktrace --info 